name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install Backend Dependencies
      - name: Install Backend
        run: |
          cd backend
          npm install

      # 4️⃣ Install Frontend Dependencies
      - name: Install Frontend
        run: |
          cd frontend
          npm install

      # 5️⃣ Build Frontend
      - name: Build React App
        run: |
          cd frontend
          npm run build

      # 6️⃣ Build Docker Images
      - name: Build Docker Images
        run: |
          docker-compose build
          
      # 7️⃣ Login to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8️⃣ Push Images
      - name: Push Docker Images
        run: |
          docker tag mern-docker-project-backend ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker tag mern-docker-project-frontend ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest